version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: kushal
      POSTGRES_PASSWORD: kushal
      POSTGRES_DB: mydatabase
    ports:
      - '5437:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: